---
Name: silverstripe-intercom-userforms
---
Form:
  extensions:
    - 'Sminnee\SilverStripeIntercom\IntercomFormExtension'
EditableFormField:
  extensions:
    - IntercomEditableFormField
UserDefinedForm:
  extensions:
    - IntercomUserDefinedFormExtension